### ISSUE TITLE
Wrong name for Hi-Computation Station Mk-III

### ISSUE THREAD

**Issue by ChromaPIE** [Zorbatron/ZBGT#58]
it's mark two *Hi-Computation Station Mk-II* now

**Comment by Zorbatron** [comment]
I don't know what you're asking? This is from the GT5u lang file:
![image](https://github.com/user-attachments/assets/637680fc-2d98-4298-b7c9-8ca58491b800)

**Comment by ChromaPIE** [comment]
```lang
metaitem.gg_circuit_1.name=Hi-Computation Station Mk-I
metaitem.gg_circuit_1.tooltip=§b93015 TFlops§r
metaitem.gg_circuit_2.name=Hi-Computation Station Mk-II
metaitem.gg_circuit_2.tooltip=§e76M Processor Units§r
metaitem.gg_circuit_3.name=Hi-Computation Station Mk-II
metaitem.gg_circuit_3.tooltip=§aInvalidate RSA§r
metaitem.gg_circuit_4.name=Hi-Computation Station Mk-IV Prototype
metaitem.gg_circuit_4.tooltip=§c56th Mersenne Prime§r
metaitem.gg_circuit_5.name=Hi-Computation Station Mk-V Finaltype
metaitem.gg_circuit_5.tooltip=§5Paradox§r
```

metaitem.gg_circuit_3.name=Hi-Computation Station Mk-II

**Comment by Zorbatron** [comment]
Oh I see it now, I'm just a little blind!

**Comment by ChromaPIE** [comment]
also im not sure if `tile.misc_casing.compact_fusion_coil_4.name` should be `Compact Fusion Coil MK-III Finaltype` instead of `MK-II`? or it's just a proto-final evolution on MK-II?
also some hyphens in the `mega_fusion` lines are wrongly written as `=`
