### ISSUE TITLE
[CRASH] There is no ore generated for material titanium

### ISSUE THREAD

**Issue by Blitzsy** [Zorbatron/ZBGT#93]
There is no ore for titanium, niobium, or ytterbium ore. These are all processed in different ways to get the required resource.

Crash Report: https://mclo.gs/OscyiaM

Problematic Lines:

https://github.com/Zorbatron/ZBGT/blob/ea6a44c6bb36ef34f9185a5839d6e2bbe5e6aa8b/src/main/java/com/zorbatron/zbgt/api/worldgen/CustomOreVeins.java#L49

https://github.com/Zorbatron/ZBGT/blob/ea6a44c6bb36ef34f9185a5839d6e2bbe5e6aa8b/src/main/java/com/zorbatron/zbgt/api/worldgen/CustomOreVeins.java#L79

https://github.com/Zorbatron/ZBGT/blob/ea6a44c6bb36ef34f9185a5839d6e2bbe5e6aa8b/src/main/java/com/zorbatron/zbgt/api/worldgen/CustomOreVeins.java#L85

https://github.com/Zorbatron/ZBGT/blob/ea6a44c6bb36ef34f9185a5839d6e2bbe5e6aa8b/src/main/java/com/zorbatron/zbgt/api/worldgen/CustomOreVeins.java#L88

**Comment by ChromaPIE** [comment]
said ores are generating with no problem on my end

**Comment by Blitzsy** [comment]
Can confirm this works as intended, there seems to be a mod conflict somewhere

**Comment by Blitzsy** [comment]
I narrowed down the issue to Forestry module within Gregtech when ZGBT is installed along side. The only I found to resolve this issue is to disable worldgen within ZGBT (`B:"Enable ore vein generation"=false`) or disable the forestry module inside of Gregtech (`B:"gregtech:fr_integration"=true`). Both of these leave holes in Gregtech or ZGBT. It would be great if you could find a way to resolve this.

**Comment by Zorbatron** [comment]
The issue is that in the forestry module, GT give titanium an ore property so that it generates all of the crushed, purified, centrifuged, etc items for the bee. But it also disables generating an actual ore block. I'm removing titanium from the vein for #94 too so it works out in the end.
